### ISSUE TITLE
Problem with google meet

### ISSUE THREAD

**Issue by gkkirilov** [anshulahuja98/account-switcher#11]
When I open direct links to google meet and not from google calendar, the switcher doesn't work as there isn't authUser in the url

**Comment by anshulahuja98** [comment]
@gkkirilov currently we only support URL based account changing. For other methods, we would have to take care of a lot of edge cases and might not be able to support it consistently as Google updates its service.

If you have any ideas on how to reliably support this, would be happy to discuss it.

**Comment by gkkirilov** [comment]
Hey, @anshulahuja98 thanks for the reply, yeah the account could be changed by adding the URL parameter "&authuser=1". and when that parameter is missing and there are no parameters in the URL, the extension doest work.

https://meet.google.com/xym-vwdc-unx - extension doesn't work
https://meet.google.com/xym-vwdc-unx?authuser=0 - extension works and can change accounts

**Comment by anshulahuja98** [comment]
Got it. 
That should work, I'll fix it.
Thanks for the suggestion.

**Comment by anshulahuja98** [comment]
Thanks for the suggestion @gkkirilov 
I'll soon publish the latest build on the chrome store

**Comment by gkkirilov** [comment]
@anshulahuja98 hey for some reason this worked and now it doesn't again

**Comment by anshulahuja98** [comment]
@gkkirilov  the build still hasn't been approved on the chrome store. Did you try the build directly from github?

**Comment by gkkirilov** [comment]
Oh maybe I was mistaken then, will wait for the build on google chrome store

**Comment by anshulahuja98** [comment]
@gkkirilov the latest build finally went live on the store. 
Hope it works for you now.

**Comment by gkkirilov** [comment]
Now it works but a glitch I found is that I need to first press the number and then press Alt for the extension to work
